name: Docker Image CI

on:
  push:
    branches: [ci]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true

      - name: Set up goproxy
        run: |
          go env -w GO111MODULE=on
          go env -w GOPROXY=https://goproxy.cn,direct

      - name: Install dependencies
        run: go get .

      - name: set env
        run: echo IMAGE_TAG=${GITHUB_REF#refs/*/}-$(TZ=Asia/Shanghai date +%Y%m%d%H%M)-$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV

      - run: echo ${{ env.IMAGE_TAG }}

      - name: static build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o main cmd/*.go

      - name: docker build
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: docker push
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: slack message
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.SLACK_WEBHOOK_API }}
          headers: '{"Content-Type": "application/json"}'
          body: '{"text": "Image Pushed: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"}'
