name: Docker Image CI

on:
  push:
    branches: [ ci ]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: static build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o main cmd/*.go

        echo IMAGE_TAG=ci-$(TZ=Asia/Shanghai date +%Y%m%d%H%M)-$(git describe --abbrev=0) >> $GITHUB_ENV

        echo ${{ env.IMAGE_TAG }}
    
    - name: docker build
      run: docker build -f Dockerfile -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
    
    - name: docker push
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

        docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    - name: slack message
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.SLACK_WEBHOOK_API }}
        headers: '{"Content-Type": "application/json"}'
        body: '{"text": "Image Pushed: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"}'
